# Generated by Django 2.1.1 on 2019-07-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190630_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
